# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanerate',
            name='user',
            field=models.CharField(default='MAMKDS', max_length=100),
            preserve_default=False,
        ),
    ]
